language: node_js
notifications:
  email: andrehenriquetatu@gmail.com    
node_js:
  - "6.11.2"
services:
  - mongodb
env:
  global:
    - NODE_ENV: test
addons:
  sauce_connect: true
before_install:
  - npm install -g bower@1.3
  - npm install -g grunt-cli@0.1
  - npm install -g karma-cli@0.0
  - npm install -g protractor@1.5
  - webdriver-manager update
  - bower install
before_script:
  - node test/data.js 
  - grunt
  - cd dist
script:
 - karma start config/karma.config.js --single-run --browsers Chrome,ChromeCanary
 - node server &
 - protractor config/protractor.js



